version: "3.9"

networks:
    backend:
        driver: bridge

volumes:
    zero2prod_data:

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    restart: always
    container_name: ${POSTGRES_CONTAINER_NAME}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_EXPOSE_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MAX_CONNECTIONS=${POSTGRES_MAX_CONNECTIONS}
    volumes:
      - ${DATA_PATH}:/var/lib/postgresql/data:Z
    command: ["postgres", "-c", "max_connections=${POSTGRES_MAX_CONNECTIONS}"]